import type { Metadata } from "next";
import SvgSprite from "../(persian)/components/svg-sprite";
import Header from "./components/header";
import "@styles/global.scss";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" prefix="og: https://ogp.me/ns#">
      <body>
        <Header />
        {children}
        <Footer />
        <SvgSprite />
      </body>
    </html>
  );
}
